### ISSUE TITLE
Handling external dependencies

### ISSUE THREAD

**Issue by athos-ribeiro** [canismarko/dungeon-sheets#2]
As pointed in PR #1, there are external dependencies, such as pdftk, which is not readily available in some linux distributions.

I do enjoy the way this package works to build PC sheets, bit I myself cannot use it in my Fedora machine. I did get to build my sheet with docker though, using the following Dockerfile:

```
FROM debian:testing
RUN apt-get update -y
RUN apt-get install -y python3 pdftk python3-pip texlive-latex-base texlive-fonts-recommended
# Here we copy the whole dungeon-sheets directory into the image
COPY dungeon-sheets /dungeon-sheets
WORKDIR /dungeon-sheets
RUN python3 setup.py install
WORKDIR /sheets
COPY my_char_sheet.py /sheets
RUN makesheets my_char_sheet.py
CMD ['makesheets']
``` 

Now, when I wnt to extract the sheet, I can just use `docker cp`. To update the sheet, I can either rebuild the image or mount a volume somewhere with the updated sheed .py file. Of course this would need some improvements on the docker image side, but this is an alternative for ppl not running debian machines.

The other way around it would be to use something other than pdftk (which depends on old libraries), but this would require a lot of work :(

**Comment by canismarko** [comment]
Yeah I agree. The biggest obstacle was that the WotC template for character sheets makes use of fillable fields in the PDF; I couldn't find a python library that supported this feature. If anyone knows of anything, the [https://github.com/canismarko/dungeon-sheets/blob/master/dungeonsheets/make_sheets.py#L275](make_pdf()) function could be modified without too much trouble.

As far as making the spellbook goes, that was mostly because it was it was fast to implement it in LaTeX.

**Comment by canismarko** [comment]
I partly solved the dependency on pdftk in https://github.com/canismarko/dungeon-sheets/commit/3368a435cb4b35b7b94ffc40583628182bf605f3. It now uses the pdfrw package as a fallback if pdftk is no available.  There are some limitations, though, as outlined in the README: 

- Produces v1.3 PDF files
- Not able to flatten PDF forms
- Will produce separate character-sheets, spell-lists and spell-books.

I'll leave this issue open for now since it would be nice to get rid of pdftk entirely someday.

**Comment by athos-ribeiro** [comment]
Wow!

Thanks for the changes :) I will test and provide feedback asap.

**Comment by canismarko** [comment]
Since there's been no comments in over a year, I'm assuming the fix is acceptable.
